### PR TITLE
added IIFE support

### PR DESCRIPTION
**Pull request by arnochauveau**

### CODE REVIEW

**Comment by MitMaro** [comment]
Thanks for the PR!

I would be happy to merge once a few items are taken care of:
- Add some tests cases to `test/lib/rules/strict-newline.js`. I think adding a case with a IIFE passing and one failing should be enough.
- Run `npm test` and ensure it passes. The coverage report should also show 100% coverage.
- Squash commits into one

If you have any questions I will be glad to answer.

**Comment by arnochauveau** [comment]
There you go!

**Comment by MitMaro** [comment]
Looks good! I'll merge and publish later today. Thanks!

**Comment by MitMaro** [comment]
Published to NPM. Thanks again for the addition!

**Pull request merged**
